
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook-receiver'

 receivers:
 - name: 'webhook-receiver'
   webhook_configs:
   - url: 'http://webhook-server:9094/webhook'
     title: 'Alert: {{ .GroupLabels.alertname }}'
     text: ' {{ range .Alerts }}{{ .Anotations.description }}{{end}}'
