version: '3.8'

services:
 grafana:
  image: grafana/grafana:latest
  ports:
   - "3000:3000"
  environment:
   - GF_SECURITY_ADMIN_PASSWORD=admin123


 webhook-server:
  build: ./webhook
  ports:
   - "9094:9094"

 prometheus:
  image: prom/prometheus:latest
  ports:
   - "9090:9090"
  #volumes:
   #- ./prometheus-ip.yml:/etc/prometheus/prometheus.yml

 node-exporter:
  image: prom/node-exporter:latest
  ports:
   - "9100:9100"
